title: "Ilie Sarpe"
description: "Projects and blog posts"
theme: minima
baseurl: ""  # leave empty for user.github.io
url: "https://iliesarpe.github.io"

# Enable MathJax globally
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Include folders
include:
  - projects
